// flow-typed signature: 3857cab30771e5c13e458e697aebd105
// flow-typed version: <<STUB>>/himalaya_v^0.3.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'himalaya'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'himalaya' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'himalaya/bin/himalaya' {
  declare module.exports: any;
}

declare module 'himalaya/docs/dist/himalaya' {
  declare module.exports: any;
}

declare module 'himalaya/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'himalaya/lib/compat' {
  declare module.exports: any;
}

declare module 'himalaya/lib/formats/util' {
  declare module.exports: any;
}

declare module 'himalaya/lib/formats/v0' {
  declare module.exports: any;
}

declare module 'himalaya/lib/formats/v1' {
  declare module.exports: any;
}

declare module 'himalaya/lib/index' {
  declare module.exports: any;
}

declare module 'himalaya/lib/lexer' {
  declare module.exports: any;
}

declare module 'himalaya/lib/parser' {
  declare module.exports: any;
}

declare module 'himalaya/lib/tags' {
  declare module.exports: any;
}

declare module 'himalaya/lib/translate/v0' {
  declare module.exports: any;
}

declare module 'himalaya/lib/translate/v1' {
  declare module.exports: any;
}

declare module 'himalaya/src/compat' {
  declare module.exports: any;
}

declare module 'himalaya/src/formats/util' {
  declare module.exports: any;
}

declare module 'himalaya/src/formats/v0' {
  declare module.exports: any;
}

declare module 'himalaya/src/formats/v1' {
  declare module.exports: any;
}

declare module 'himalaya/src/index' {
  declare module.exports: any;
}

declare module 'himalaya/src/lexer' {
  declare module.exports: any;
}

declare module 'himalaya/src/parser' {
  declare module.exports: any;
}

declare module 'himalaya/src/tags' {
  declare module.exports: any;
}

declare module 'himalaya/src/translate/v0' {
  declare module.exports: any;
}

declare module 'himalaya/src/translate/v1' {
  declare module.exports: any;
}

declare module 'himalaya/translate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'himalaya/bin/himalaya.js' {
  declare module.exports: $Exports<'himalaya/bin/himalaya'>;
}
declare module 'himalaya/docs/dist/himalaya.js' {
  declare module.exports: $Exports<'himalaya/docs/dist/himalaya'>;
}
declare module 'himalaya/gulpfile.babel.js' {
  declare module.exports: $Exports<'himalaya/gulpfile.babel'>;
}
declare module 'himalaya/lib/compat.js' {
  declare module.exports: $Exports<'himalaya/lib/compat'>;
}
declare module 'himalaya/lib/formats/util.js' {
  declare module.exports: $Exports<'himalaya/lib/formats/util'>;
}
declare module 'himalaya/lib/formats/v0.js' {
  declare module.exports: $Exports<'himalaya/lib/formats/v0'>;
}
declare module 'himalaya/lib/formats/v1.js' {
  declare module.exports: $Exports<'himalaya/lib/formats/v1'>;
}
declare module 'himalaya/lib/index.js' {
  declare module.exports: $Exports<'himalaya/lib/index'>;
}
declare module 'himalaya/lib/lexer.js' {
  declare module.exports: $Exports<'himalaya/lib/lexer'>;
}
declare module 'himalaya/lib/parser.js' {
  declare module.exports: $Exports<'himalaya/lib/parser'>;
}
declare module 'himalaya/lib/tags.js' {
  declare module.exports: $Exports<'himalaya/lib/tags'>;
}
declare module 'himalaya/lib/translate/v0.js' {
  declare module.exports: $Exports<'himalaya/lib/translate/v0'>;
}
declare module 'himalaya/lib/translate/v1.js' {
  declare module.exports: $Exports<'himalaya/lib/translate/v1'>;
}
declare module 'himalaya/src/compat.js' {
  declare module.exports: $Exports<'himalaya/src/compat'>;
}
declare module 'himalaya/src/formats/util.js' {
  declare module.exports: $Exports<'himalaya/src/formats/util'>;
}
declare module 'himalaya/src/formats/v0.js' {
  declare module.exports: $Exports<'himalaya/src/formats/v0'>;
}
declare module 'himalaya/src/formats/v1.js' {
  declare module.exports: $Exports<'himalaya/src/formats/v1'>;
}
declare module 'himalaya/src/index.js' {
  declare module.exports: $Exports<'himalaya/src/index'>;
}
declare module 'himalaya/src/lexer.js' {
  declare module.exports: $Exports<'himalaya/src/lexer'>;
}
declare module 'himalaya/src/parser.js' {
  declare module.exports: $Exports<'himalaya/src/parser'>;
}
declare module 'himalaya/src/tags.js' {
  declare module.exports: $Exports<'himalaya/src/tags'>;
}
declare module 'himalaya/src/translate/v0.js' {
  declare module.exports: $Exports<'himalaya/src/translate/v0'>;
}
declare module 'himalaya/src/translate/v1.js' {
  declare module.exports: $Exports<'himalaya/src/translate/v1'>;
}
declare module 'himalaya/translate.js' {
  declare module.exports: $Exports<'himalaya/translate'>;
}
