// flow-typed signature: 8f497e791463caf7164272ca64c75f05
// flow-typed version: <<STUB>>/memory-cache_v^0.2.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memory-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'memory-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'memory-cache/gulpfile' {
  declare module.exports: any;
}

declare module 'memory-cache/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'memory-cache/gulpfile.js' {
  declare module.exports: $Exports<'memory-cache/gulpfile'>;
}
declare module 'memory-cache/index' {
  declare module.exports: $Exports<'memory-cache'>;
}
declare module 'memory-cache/index.js' {
  declare module.exports: $Exports<'memory-cache'>;
}
declare module 'memory-cache/test.js' {
  declare module.exports: $Exports<'memory-cache/test'>;
}
