// flow-typed signature: 9031cd5e1c4d4d4c6457a08fd3ddde65
// flow-typed version: <<STUB>>/micro-joi_v^3.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micro-joi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'micro-joi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'micro-joi/index' {
  declare module.exports: $Exports<'micro-joi'>;
}
declare module 'micro-joi/index.js' {
  declare module.exports: $Exports<'micro-joi'>;
}
