// flow-typed signature: 34dcd3afb2c2598b5179fccc3e1191b7
// flow-typed version: <<STUB>>/micro-dev_v^1.3.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micro-dev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'micro-dev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'micro-dev/bin/micro-dev' {
  declare module.exports: any;
}

declare module 'micro-dev/lib/error' {
  declare module.exports: any;
}

declare module 'micro-dev/lib/help' {
  declare module.exports: any;
}

declare module 'micro-dev/lib/listening' {
  declare module.exports: any;
}

declare module 'micro-dev/lib/log' {
  declare module.exports: any;
}

declare module 'micro-dev/lib/serve' {
  declare module.exports: any;
}

// Filename aliases
declare module 'micro-dev/bin/micro-dev.js' {
  declare module.exports: $Exports<'micro-dev/bin/micro-dev'>;
}
declare module 'micro-dev/lib/error.js' {
  declare module.exports: $Exports<'micro-dev/lib/error'>;
}
declare module 'micro-dev/lib/help.js' {
  declare module.exports: $Exports<'micro-dev/lib/help'>;
}
declare module 'micro-dev/lib/listening.js' {
  declare module.exports: $Exports<'micro-dev/lib/listening'>;
}
declare module 'micro-dev/lib/log.js' {
  declare module.exports: $Exports<'micro-dev/lib/log'>;
}
declare module 'micro-dev/lib/serve.js' {
  declare module.exports: $Exports<'micro-dev/lib/serve'>;
}
